# Generated by Django 5.0.6 on 2024-07-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.CharField(editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
