# Generated by Django 3.2.25 on 2024-09-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_alter_playlist_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField()),
                ('spotify_url', models.URLField()),
                ('performer', models.CharField(max_length=255)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
