# Generated by Django 3.2.25 on 2024-10-02 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0004_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episode', to='playlists.playlist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='playlists.playlist'),
        ),
    ]
